site_name: 'First Baptist Church Muncie'
site_url: 'http://demo.fbcmuncie.org'
markdown: rdiscount
rdiscount:
    extensions: [smart]
permalink: /blog/:year/:month/:day/:title


mini_magick:
    thumbnail:
        source: img/photos/original
        destination: img/photos/thumbnail
        resize: "100x100"
    medium:
        source: img/photos/original
        destination: img/photos/medium
        resize: "420x308"