site_name: 'First Baptist Church Muncie'
url: fbcmuncie.org
markdown: rdiscount
rdiscount:
    extensions: [smart]
permalink: /:categories/:year/:month/:day/:title

# Facebook comments
facebook_appid: 397803531137
google_analytics: UA-34472663-2
